<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Orders Report - {{ now()->format('Y-m-d') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-right {
            text-align: right;
        }
        .badge {
            padding: 3px 8px;
            border-radius: 3px;
            font-size: 11px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .badge-success {
            background-color: #d4edda;
            color: #155724;
        }
        .badge-primary {
            background-color: #cce5ff;
            color: #004085;
        }
        .badge-warning {
            background-color: #fff3cd;
            color: #856404;
        }
        .badge-danger {
            background-color: #f8d7da;
            color: #721c24;
        }
        .badge-info {
            background-color: #d1ecf1;
            color: #0c5460;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 11px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Orders Report</h1>
        <p>Generated on: {{ now()->format('F j, Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Customer</th>
                <th>Date</th>
                <th>Payment Status</th>
                <th>Delivery Status</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
            <tr>
                <td>#{{ $order->id }}</td>
                <td>
                    {{ $order->first_name }} {{ $order->last_name }}
                    <br>
                    <small>{{ $order->email }}</small>
                </td>
                <td>{{ $order->created_at->format('M d, Y h:i A') }}</td>
                <td>
                    @if($order->status == 'completed')
                        <span class="badge badge-success">Paid</span>
                    @elseif($order->status == 'processing')
                        <span class="badge badge-primary">Processing</span>
                    @elseif($order->status == 'cancelled')
                        <span class="badge badge-danger">Cancelled</span>
                    @else
                        <span class="badge badge-warning">Cash on delivery</span>
                    @endif
                </td>
                <td>
                    @if($order->delivery_status == 'delivered')
                        <span class="badge badge-success">Delivered</span>
                    @elseif($order->delivery_status == 'shipped')
                        <span class="badge badge-info">Shipped</span>
                    @elseif($order->delivery_status == 'processing')
                        <span class="badge badge-primary">Processing</span>
                    @elseif($order->delivery_status == 'cancelled')
                        <span class="badge badge-danger">Cancelled</span>
                    @endif
                </td>
                <td class="text-right">${{ number_format($order->total, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Orders: {{ $orders->count() }} | Generated by {{ config('app.name') }}</p>
    </div>
</body>
</html>
